#!/usr/bin/with-contenv bash

if [[ -z "${S3_URL}" ]]; then
  exec s3fs -f $BUCKET:/Plex /data -o passwd_file=/passwd-s3fs -o allow_other
else
  exec s3fs -f $BUCKET:/Plex /data -o passwd_file=/passwd-s3fs -o allow_other -o url=$S3_URL
fi
